### ISSUE TITLE
Does not work with ruby 1.8.x

### ISSUE THREAD

**Issue by ghost** [devthenet/voyeur#2]
Hi.

When doing:

require 'Voyeur'

It breaks at something like:

Voyeur::Video.new( filename: path_to_file ).convert( to: :mp4 )  

The culprit in question is the hash format as I will illustrate just with one example:

to: :mp4

Is valid in Ruby 1.9.x but not in Ruby 1.8.x

:to => mp4

Would work in Ruby 1.8.x

I can understand if you do not want to allow this format.

I suggest to, if Ruby 1.8.x is not supported, add a disclaimer in the README so that people who still use Ruby 1.8.x could avoid the frustration of testing this project only to notice that it will not work without patching the source.

Thank you for considering.

**Comment by brvtl** [comment]
@shevegen Thanks for the feedback - We didn't support 1.8.x because it is currently being phased out ( http://www.ruby-lang.org/en/news/2011/10/06/plans-for-1-8-7/ ). 

We should have, however, explicitly stated 1.9 only.
I will patch it and release a branch compatible with 1.8.x, however, that branch will probably receive no love in the future :(
